---

- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_os_family == "RedHat"

- name: Install FreeIPA server packages
  package:
    name: "{{ freeipa_server_pkgs }}"
    state: present
    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"

- name: Install FreeIPA server pip dependencies
  pip:
    name: "{{ freeipa_server_pip_pkgs }}"
    state: present
