---

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: dependencies.yml

- include_tasks: install-pkgs.yml

- include_tasks: freeipa-server-install.yml
