---

- name: Gather OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - vars

- name: Check installation type
  fail:
    msg: "freeipa_server_type: '{{ freeipa_server_type }}' is not a valid installation type"
  when: freeipa_server_type not in freeipa_server_supported_types

- name: Check freeipa_server_master_fqdn is not empty
  fail:
    msg: "'freeipa_server_master_fqdn' is empty"
  when:
    - freeipa_server_type == 'replica'
    - freeipa_server_master_fqdn | length == 0

- include_tasks: dependencies.yml

- include_tasks: install-pkgs.yml
  when: freeipa_server_install_pkgs

- include_tasks: preinst.yml

- include_tasks: freeipa-server-install.yml

- include_tasks: postinst.yml
